# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f0444807b1b0b315fe882589fbbd22430b973a237faa36fb2d19ebe36cc53b627cb4c1f4bdea1fb75f087c32ee49ab4776266844cb07ee7f3610e28885b4e97

test:
  secret_key_base: a7801ce999f53a9f98e225a79e46ecad031952cee90138590fcdd3e8664a9808af4913389e77ff7d7643eaa9f3ea4ddafb85301882b4182e0cb21ef8cf71e3c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
